# Generated by Django 6.0.6 on 2026-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='Boshlovchi', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
